apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  backoffLimit: 3        # ile razy retry w razie b³êdu
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: hello
        image: busybox
        command:
          - sh
          - -c
          - |
            echo "Hello from Job!"
            date
