apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: |
    Server=<host>,<port>;Database=<db>;User Id=<user>;Password=<password>;Encrypt=False;TrustServerCertificate=True;
  JWT__PrivateKeyPem: |
    <base64 klucza prywatnego RSA PKCS#1>
